### ISSUE TITLE
Suggestion: mesh-ui search should not sort results by 'created"

### ISSUE THREAD

**Issue by lakaimdb** [gentics/mesh#1140] opened 2020-09-30 14:13 UTC
## Gentics Mesh Version, operating system, or hardware.
- v1.70

## Operating System
- Docker image

## Problem
Sorting search results in mesh-ui by 'created' leads to less relevant results being show at the top of the list. Most relevant results might get supressed.

## Reproducer
Just use the search functionality of the mesh-ui. This invokes a elastic query like so
`{"query":{"query_string":{"query":"react"}},"sort":[{"created":"asc"}]}`

## Expected behaviour and actual behaviour
`{"query":{"query_string":{"query":"react"}}}`

**Comment by Jotschi** [comment] 2020-09-30 15:28
I think this issue will be adressed via https://github.com/gentics/mesh-ui/pull/332.

Duplicate of https://github.com/gentics/mesh-ui/issues/331

**Closed by Jotschi** 2020-09-30 15:28 UTC
