### ISSUE TITLE
updating project name looses the track of tags, tagfamilies, nodes, microschemas, schemas etc

### ISSUE THREAD

**Issue by virbas** [gentics/mesh#414] opened 2018-05-15 15:59 UTC
Version: v0.19.2
OS: MacOS 10.13.4

let's say we have a project { uuid: 123, name: "demo" }
**1) we make a POST:**
url: api/v1/projects/123}
Request body: {"name":"demo_new"}

**2) GET api/v1/projects returns:**
{..., uuid: 123, name: "demo_new", ...}

**3) All the following requests to api/v1/demo_new/[children, schemas, microschemas, tagFamilies] fails with 404:**
{
  "i18nParameters" : [ "demo" ],
  "properties" : { },
  "type" : "generic_error",
  "message" : "Project could not be found: \"demo\""
}

**Note that the error message still displays an old project name "demo"**

**Comment by Jotschi** [comment] 2018-05-15 16:26
@virbas Which version of Gentics Mesh?

**Comment by virbas** [comment] 2018-05-15 17:49
@Jotschi v0.19.2

**Comment by Jotschi** [comment] 2018-05-15 18:28
That's a known bug in vert.x. happens only if you append something to the original project name.

**Comment by Jotschi** [comment] 2019-06-12 17:44
Duplicate of #369

**Closed by Jotschi** 2019-06-12 17:44 UTC
Labels: bug
