### ISSUE TITLE
How can I sort the result by GraphQL?

### ISSUE THREAD

**Issue by suihanhbr** [gentics/mesh#682] opened 2019-03-22 13:15 UTC
As the title.

**Comment by Jotschi** [comment] 2019-03-22 13:20
Duplicate of #27

**Comment by Jotschi** [comment] 2019-03-22 13:21
Sorting is currently not possible via GraphQL. As a workaround you could use Elasticsearch queries and sort using those.

**Comment by suihanhbr** [comment] 2019-03-22 13:23
Can you show me any example?

**Comment by Jotschi** [comment] 2019-03-22 14:06
Sorting all nodes by creation date:

```
> POST /api/v1/demo/search/nodes HTTP/1.1
> Host: demo.getmesh.io
> User-Agent: insomnia/5.12.3
> Content-Type: application/json
> Accept: */*
> Content-Length: 172
| {
|   "sort" : {
|      "created" : { "order" : "asc" }
|   },
|   "query":{
|     "bool" : {
|       "must" : {
|         "term" : { "schema.name.raw" : "vehicle" }
|        }
|     }
|   }
| }
```

Sorting by string fields is currently complicated since this requires custom mappings to be added in your elasticsearch mapping.

**Comment by suihanhbr** [comment] 2019-03-22 14:47
Thank you . I do ti like in my project.
```
{
  # Get all nodes and apply filter
  nodes(page :1,perPage:5, query:"{ \"sort\" : {      \"fields.date\" : { \"order\" : \"asc\" }  },  \"query\":{\"bool\" : {       \"must\" : {        \"term\" : { \"schema.name.raw\" : \"config\" }       }     }   }}") {
    currentPage
    
    size
    hasNextPage
    elements {
      uuid
      displayName
      fields {
        ... on config {
          name
        }
      }
    }
  }
}
```

**Comment by Jotschi** [comment] 2019-03-22 14:50
@suihanhbr The query seems valid. Let me know if you have other questions. I'm closing this issue so far. Thank you.

**Closed by Jotschi** 2019-03-22 14:50 UTC
Labels: question
