### ISSUE TITLE
Gentic Mesh Crashs at Startup

### ISSUE THREAD

**Issue by sunsus** [gentics/mesh#647] opened 2019-02-11 14:51 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.29.10

## Operating System
- Linux (Kubernetis)

## JVM
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)

## Problem

```
SEVERE: Exception `18D910B3` in storage `plocal:/graphdb/storage`: 3.0.14 - Veloce (build ac128c5a9ba4c6dc9d25a32b92962d8863774423, branch 3.0.x)
--
  | com.orientechnologies.orient.core.exception.OStorageException: Storage storage is not opened.
  | DB name="storage"
  | at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpenness(OAbstractPaginatedStorage.java:4264)
  | at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:1869)
  | at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterIdByName(ODatabaseDocumentAbstract.java:946)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.getNextAvailableClusterName(OSchemaEmbedded.java:381)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.createClusters(OSchemaEmbedded.java:373)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.doCreateClass(OSchemaEmbedded.java:269)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.createClass(OSchemaEmbedded.java:43)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:232)
  | at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:88)
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1362)
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1359)
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1868)
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1359)
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1328)
  | at com.gentics.mesh.graphdb.OrientDBDatabase.addVertexType(OrientDBDatabase.java:721)
  | at com.gentics.mesh.graphdb.OrientDBDatabase.addVertexType(OrientDBDatabase.java:742)
  | at com.gentics.mesh.core.data.job.impl.NodeMigrationJobImpl.init(NodeMigrationJobImpl.java:41)
  | at com.gentics.mesh.core.data.impl.DatabaseHelper.init(DatabaseHelper.java:138)
  | at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:206)
  | at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:299)
  | at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134)
  | at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98)
  | at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59)
  |  
  | 14:48:02.557 [Spooky Claydol] ERROR [main] - Error while starting mesh
  | java.lang.NullPointerException: null
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:394) ~[mesh-server-0.29.10.jar:na]
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1180) ~[mesh-server-0.29.10.jar:na]
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1173) ~[mesh-server-0.29.10.jar:na]
  | at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1166) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.graphdb.OrientDBDatabase.addVertexType(OrientDBDatabase.java:734) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.graphdb.OrientDBDatabase.addVertexType(OrientDBDatabase.java:742) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.core.data.job.impl.NodeMigrationJobImpl.init(NodeMigrationJobImpl.java:41) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.core.data.impl.DatabaseHelper.init(DatabaseHelper.java:138) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:206) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:299) ~[mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:134) [mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:98) [mesh-server-0.29.10.jar:na]
  | at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:59) [mesh-server-0.29.10.jar:na]
  | 14:48:02.558 [Spooky Claydol] INFO  [main] - Mesh shutting down...
```

## Reproducer
Start mesh with an emtpy graphdb dir

**Comment by Jotschi** [comment] 2019-02-12 09:19
What storage system are you using? Is this error persistent? I can't reproduce it locally.

**Comment by sunsus** [comment] 2019-02-19 08:00
We are using NFS. Yes this error is perisitent.
We can reproduce it evertime we try to run a new instance on OpenShift (Kubernetis)

**Comment by Jotschi** [comment] 2019-02-19 08:54
@sunsus Don't use NFS for databases. We had bad experience when using NFS for Mesh / OrientDB.

**Comment by mephinet** [comment] 2019-02-19 10:23
From the [OrientDB documentation](http://orientdb.com/docs/3.0.x/internals/Paginated-Local-Storage.html#file-system):
> Since PLOCAL is disk-based, all pages are flushed to physical files. You can specify any mounted partitions on your machine, backed by Disks, SSD, Flash Disks or DRAM.

**Comment by Jotschi** [comment] 2019-03-14 09:59
I'm closing this issue since it is not reproducible and NFS often causes issues with data storages which open a lot of file handles and need direct IO support to work properly.

**Closed by Jotschi** 2019-03-14 09:59 UTC
