### ISSUE TITLE
Permissions not set as expected

### ISSUE THREAD

**Issue by Kinbaum** [gentics/mesh#698] opened 2019-04-12 18:12 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.31.4

## Problem
- v0.31.4 fixed an issue with read vs read published permissions with the Tag query. v0.31.3 fixed the same issue with the Node query. However, if you submit an Elasticsearch string to the Nodes query, you will get the same permissions issue.

## Reproducer
- Uncheck read permission from anonymous user. Make sure only read published is checked.
- Open the Graphiql tool to test out a query
- Use the following query or something similar to see that no nodes return

```
{
  nodes(query: "{\"query\":{\"nested\":{\"path\":\"tags\",\"query\":{\"bool\":{\"should\":[{\"match_phrase\":{\"tags.name\":\"Container Orchestration\"}},{\"match_phrase\":{\"tags.name\":\"Automation\"}}]}}}}}") {
    elements {
      uuid
    }
  }
}
```

## Expected behaviour and actual behaviour
- The expected behavior is to see a list of published nodes returned with their `uuid` field.
- The current behavior is that you can only execute this query anonymously if that user has read permission on every node, which breaks the concept of draft vs published.

**Comment by Jotschi** [comment] 2019-05-07 12:47
I think the problem is located here: 
https://github.com/gentics/mesh/blob/hotfix/elasticsearch/src/main/java/com/gentics/mesh/search/index/AbstractTransformer.java#L120

The permissions should be added according to the target index of the doc (e.g. `read_published` and `read` for published index docs. Documents for the draft index should only use `read`).

**Comment by MatthewKinbaum** [comment] 2019-05-11 03:31
Do you have an ETA as to when this will be fixed? I saw it’s still present in version 0.32

**Comment by Jotschi** [comment] 2019-05-11 16:29
I'll try to add the fix to the release for next week. I already have a good understanding whats wrong. I think most of the time will be spend on tests instead of the fix.

**Comment by MatthewKinbaum** [comment] 2019-05-11 17:32
Sounds good. Thank you

**Comment by Jotschi** [comment] 2019-05-13 07:41
@MatthewKinbaum Which query parameters are you using when posting the graphql query?

**Comment by MatthewKinbaum** [comment] 2019-05-13 12:05
I call this endpoint: `/api/v1/{project}/graphql/browser/` with the exact query I pasted up above:
```
{
  nodes(query: "{\"query\":{\"nested\":{\"path\":\"tags\",\"query\":{\"bool\":{\"should\":[{\"match_phrase\":{\"tags.name\":\"Container Orchestration\"}},{\"match_phrase\":{\"tags.name\":\"Automation\"}}]}}}}}") {
    elements {
      uuid
    }
  }
}
```

**Comment by Jotschi** [comment] 2019-05-13 12:34
Can you confirm that the problem does not happen for you when you append `?version=published` to the POST request?

**Comment by MatthewKinbaum** [comment] 2019-05-13 14:25
I changed the endpoint to the following:
`/api/v1/devops/graphql?version=published`

I'm still seeing the same unpublished content showing

**Comment by MatthewKinbaum** [comment] 2019-05-20 17:27
Update:

I was able to use the query parameter as a temporary workaround. We were proxying our gentics environment using the req.baseUrl, so the params were not being included.

**Comment by Jotschi** [comment] 2019-05-20 17:38
@MatthewKinbaum I have started to work on a unit test to reproduce the issue. I unfortunately did not yet have time to pick up the work on the test.

https://github.com/gentics/mesh/pull/735/files

**Comment by Jotschi** [comment] 2019-05-28 13:46
@MatthewKinbaum We want to take a closer look at this problem. It should be possible to filter by published and not published nodes. This is currently not directly possible with GraphQL instead the query parameter can be used as a workaround. The current plan is to add the missing filter to the filter arguments.

**Comment by janis91** [comment] 2019-10-22 09:05
@Jotschi is there already an ETA for this feature?

**Comment by Jotschi** [comment] 2019-10-22 09:21
@janis91 Sorry. I don't have an ETA for this due to changing priorities.

**Comment by Jotschi** [comment] 2019-12-09 10:46
@janis91 @Kinbaum We have reviewed this issue and concluded that the mentioned permission problems have been solved and are now covered by tests. We'll cover the enhancements for the GraphQL API in https://github.com/gentics/mesh-incubator/issues/57

Please file a new issue if you encounter any other permission issue. Thanks

**Closed by Jotschi** 2019-12-09 10:46 UTC
Labels: bug, f/elasticsearch, f/graphql, major
