### ISSUE TITLE
Link Resolving always adds hostname of default branch

### ISSUE THREAD

**Issue by npomaroli** [gentics/mesh#548] opened 2018-11-15 08:57 UTC
When loading a node from a branch different from the latest branch with link resolving (type SHORT), the resolved links will contain the hostname of the latest branch, but not the used branch.

**Comment by Jotschi** [comment] 2019-06-18 13:37
I can't reproduce this issue using Mesh 0.36.1. I added a test which:

* Create project (included default branch)
* Create test branch (not set to latest)
* Create node in test branch which contains link to node of initial branch (node was also migrated to new branch)
* Load node of test branch and resolve links
* Assert that link uses the current branch host name

**Comment by Jotschi** [comment] 2019-06-18 13:47
Issue has already been fixed in 0.28.0

**Closed by Jotschi** 2019-06-18 13:47 UTC
Labels: bug, minor
