### ISSUE TITLE
Nodes disappear from search after microschema update

### ISSUE THREAD

**Issue by elbird** [gentics/mesh#122] opened 2017-09-05 08:44 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.9.27

## Problem

I updated a microschema which threw an exception (see below). After this all nodes which used this microschema where not available in the search. Reindexing all data also threw an exception. (see below)

Exception after microschema update:
``````
09:41:48.986 [Dumbstruck Monferno] ERROR [vert.x-worker-thread-10] [NodeMigrationVerticle.java:345] - Migration for schema/microschema {2aeec206b6f54074aec206b6f560740c} failed with error.
com.gentics.mesh.core.rest.error.GenericRestException: 400 Bad Request Target version uuid {d8ed12dbf1724c73ad12dbf1720c7362} of microschema {2aeec206b6f54074aec206b6f560740c} could not be found. params {}
        at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:85) ~[mesh-server-0.9.27.jar:na]
        at com.gentics.mesh.core.verticle.node.NodeMigrationVerticle.lambda$null$2(NodeMigrationVerticle.java:219) ~[mesh-server-0.9.27.jar:na]
        at com.gentics.mesh.graphdb.spi.Database.lambda$tx$1(Database.java:93) ~[mesh-server-0.9.27.jar:na]
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:521) ~[mesh-server-0.9.27.jar:na]
        at com.gentics.mesh.graphdb.spi.Database.tx(Database.java:92) ~[mesh-server-0.9.27.jar:na]
        at com.gentics.mesh.core.verticle.node.NodeMigrationVerticle.lambda$registerMicroschemaMigration$3(NodeMigrationVerticle.java:196) ~[mesh-server-0.9.27.jar:na]
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212) ~[mesh-server-0.9.27.jar:na]
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191) ~[mesh-server-0.9.27.jar:na]
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:524) ~[mesh-server-0.9.27.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[mesh-server-0.9.27.jar:na]
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[mesh-server-0.9.27.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
``````

Exception when reindexing:
``````
09:51:53.093 [Dumbstruck Monferno] ERROR [elasticsearch[Dumbstruck Monferno][listener][T#1]] [ElasticSearchProvider.java:354] - Adding object {c2cf78118db24c928
f78118db23c9264-de:node} to index failed. Duration 64[ms]
java.lang.IllegalArgumentException: mapper [fields.ancillaryExpenses] of different type, current_type [double], merged_type [long]
        at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:378) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.doMerge(NumberFieldMapper.java:301) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:364) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:53) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:60) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.ObjectMapper.doMerge(ObjectMapper.java:528) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.RootObjectMapper.doMerge(RootObjectMapper.java:277) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.ObjectMapper.merge(ObjectMapper.java:501) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.object.RootObjectMapper.merge(RootObjectMapper.java:272) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:112) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:376) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:260) ~[mesh-server-0.9.27.jar:n
a]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.j
ava:231) ~[mesh-server-0.9.27.jar:na]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
 ~[mesh-server-0.9.27.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
``````
The same exception is thrown for also for other nodes (e.g. 535016673ab94dd09016673ab96dd0e2)  and different fields (e.g. 'fields.rent')

The zipped data dir can be downloaded here: https://filebox.apa-it.at/index.php/s/ImfljjYBnRq99IA

**Comment by sebastianvogel** [comment] 2017-09-05 08:55
What is also not good is that the whole reindex operation fails when one exception occurs. One corrupt Node can render a whole Mesh-Installation unusable.

**Comment by Jotschi** [comment] 2017-09-05 13:28
I created related issues #124  and #123 - Additionally I fixed a few bugs which prevents the node migration from being processed correctly. These fixed will be included in the next release.

**Comment by Jotschi** [comment] 2019-06-26 19:53
Duplicate of #777

**Closed by Jotschi** 2019-06-26 19:53 UTC
Labels: bug, f/elasticsearch
