### ISSUE TITLE
Restore fails with 504 Gateway Time-out

### ISSUE THREAD

**Issue by MehrCurry** [gentics/mesh#510] opened 2018-10-04 10:42 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.24.1

## Operating System
- OpenShift

## JVM
```
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_01_00-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
```
## Problem
Restore fails with 504 Gateway Time-out

Either via curl or via Postman. When i start a restore process the log shows that some file have been uncompressed and the it stops with an Exception.

```
- Uncompressing file updateschemachangeimpl.cpm...
- Uncompressing file jobrootimpl_1.cpm...
- Uncompressing file microschemacontainerversionimpl.cpm...
- Uncompressing file has_field_6.cpm...
- Uncompressing file has_update_permission_7.cpm...
- Uncompressing file binaryimpl_6.cpm...
- Uncompressing file has_publish_permission_7.pcl...
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Storage 'storage' was not closed properly. Will try to recover from write ahead log...
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Looking for last checkpoint...
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} FULL checkpoint found.
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Data restore procedure from full checkpoint is started. Restore is performed from LSN LSN{segment=51, position=28}
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=storage}} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=LSN{segment=51, position=52}} will be skipped during data restore
Oct 04, 2018 10:35:58 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} 1 operations were processed, current LSN is LSN{segment=51, position=52} last LSN is LSN{segment=51, position=52}
Oct 04, 2018 10:36:00 AM com.orientechnologies.common.log.OLogManager log
INFO: $ANSI{green {db=storage}} Storage data recover was completed
Oct 04, 2018 10:36:01 AM com.orientechnologies.common.log.OLogManager log
INFO: Storage 'plocal:/data/storage' is opened under OrientDB distribution : 2.2.34 (build f340442755a31eabc91b87cb3ef99eda5cee6ebd, branch 2.2.x)
10:36:01.886 [Booming Audino] INFO  [vert.x-worker-thread-12] - Added project router {tui}
10:36:01.889 [Booming Audino] INFO  [vert.x-worker-thread-12] - Added project router {playground}
10:36:01.892 [Booming Audino] INFO  [vert.x-worker-thread-12] - Added project router {assets}
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:189)
	at com.gentics.mesh.context.impl.InternalRoutingActionContextImpl.send(InternalRoutingActionContextImpl.java:80)
	at com.gentics.mesh.handler.ActionContext.send(ActionContext.java:78)
	at com.gentics.mesh.context.AbstractInternalActionContext.send(AbstractInternalActionContext.java:32)
	at com.gentics.mesh.core.endpoint.admin.AdminHandler.lambda$handleRestore$6(AdminHandler.java:108)
```
Only some parts have been restored after that.

## Reproducer

create backup and then restore

## Expected behaviour and actual behaviour

Full Restore with Status 2xx

**Comment by Jotschi** [comment] 2018-10-04 11:01
We have tests in place to check this feature. What kind of contents were missing after the restore?

**Comment by Jotschi** [comment] 2018-10-19 15:45
I assume the error 504 happens because the Gentics Mesh API does not directly respond to the backup & restore requests. Those requests are currently blocking and return once they have finished. We will update those endpoints and run the backup restore process in the background. I assume you managed to invoke the restore while the backup was still running. We will add safeguards to prevent such actions in the future.

**Comment by Jotschi** [comment] 2019-03-14 09:55
Duplicate of #575

**Closed by Jotschi** 2019-03-14 09:55 UTC
Labels: bug, f/admin, f/clustering
