### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by sunsus** [gentics/mesh#554] opened 2018-11-15 14:27 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.27.1 2018-10-31T16:19:02T

## Operating System
- Linux

## JVM
- Open JDK 1.8.0_100

## Problem
SEVERE: $ANSI{green {db=storage}} Exception during index 'e.has_field_container_webrootpathinfoindex' creation
--
  | com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #115:6: found duplicated key 'OCompositeKey{keys=[305e720ab4c64b049e720ab4c6db0441, D, ]}' in index 'e.has_field_container_webrootpathinfoindex' previously assigned to the record #115:0
  | DB name="storage" INDEX=e.has_field_container_webrootpathinfoindex RID=#115:0

## Reproducer
Not posible
## Expected behaviour and actual behaviour
Crash of Applicationm, no startup

**Comment by Jotschi** [comment] 2018-11-15 16:18
@sunsus Can you provide the full Mesh Startup log?

**Comment by Jotschi** [comment] 2018-11-20 20:01
Seems to be same problem which is being reported in #545

**Comment by Jotschi** [comment] 2018-11-20 23:57
I was able to reproduce the issue. I'll check whether a workaround is possible or whether I need to prepare a fix for the next release.

**Comment by Jotschi** [comment] 2018-11-21 00:08
@sunsus Please see https://github.com/gentics/mesh/issues/546 for an explanation - I'll let you know once a fix is ready.

**Comment by Jotschi** [comment] 2018-11-26 10:19
@sunsus I fixed the bug. The fix will be included in the next release.

**Comment by Jotschi** [comment] 2018-11-26 11:52
@sunsus Fix is included in 0.28.1

**Closed by Jotschi** 2018-11-26 11:52 UTC
Labels: bug, f/webroot
