### ISSUE TITLE
Creating a lot of node and update their binary field seems to stuck server mesh api

### ISSUE THREAD

**Issue by cschockaert** [gentics/mesh#573] opened 2018-11-21 09:09 UTC
## Gentics Mesh Version, operating system, or hardware.
- v0.27.2

## Operating System
- MacOSX

## JVM
- java 11 mesh rest client

## Problem

I got a batch that is creating a lot of node:

```

private Mono<NodeResponse> createWithDummyBinary(GetmeshNodeUpdateRequest nodeRequest) {

        return RxJava2Adapter.singleToMono(masterMeshRestClient
                .createNode(nodeRequest.getUuid(), getMeshProperties.getProjectName(), (NodeCreateRequest) nodeRequest.getNode())
                .toSingle()).flatMap(nodeResponse -> {
            byte[] data = missingLogo.get();
            if (data != null) {
                Buffer fileData = Buffer.buffer(data);
                return RxJava2Adapter.singleToMono(masterMeshRestClient.updateNodeBinaryField(getMeshProperties.getProjectName(),
                        nodeResponse.getUuid(), nodeResponse.getLanguage(), nodeResponse.getVersion(),
                        "picto", fileData, MISSING_IMAGE_90_X_90_JPG, MISSING_IMAGE_CONTENTTYPE).toSingle());
            } else {
                log.warn("data is missing for empty logo");
                return Mono.just(nodeResponse);
            }
        });
    }

```

## Reproducer

After a while, about 20 nodes get created fine then i experience some problem client and server side.
request are blocked and getmesh api is not responding anymore, i dont have any exception server side, i must restart the getmesh server
if i dont create binaries, all is working fine (i can create update node in the batch without no pb at all)

i think there is something that stuck getmesh when we create a lot of node and update them with the same binary.

client side, all i see is exception like : io.vertx.core.VertxException: Connection was closed (i think it's the 10 sec timeout i putted under meshRestClient

## Expected behaviour and actual behaviour

getmesh api should not getting stucked.

**Comment by cschockaert** [comment] 2018-11-21 09:11
when i try to kill docker i get stuck too:

```
08:50:08.958 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-0] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:50:08 GMT] "POST /api/v1/content/nodes/affd28139ee94ec8ad6613f09fd58121 HTTP/1.1" 201 2946 "-" "-"
08:50:08.987 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-6] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:50:08 GMT] "POST /api/v1/content/nodes/bc1cc77ac23d45cd846ce050c66fcc0b HTTP/1.1" 201 2785 "-" "-"
08:50:09.083 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-2] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:50:08 GMT] "POST /api/v1/content/nodes/5326bcfc79344fdc807de1703be7c6c7 HTTP/1.1" 201 2859 "-" "-"
08:50:09.124 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-4] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:50:08 GMT] "POST /api/v1/content/nodes/ed5e4d64319241f6a4dfaa9396d8498c HTTP/1.1" 201 2865 "-" "-"





08:56:55.785 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-2] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:56:55 GMT] "GET /api/v1/admin/status HTTP/1.1" 200 24 "-" "-"
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:547)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:188)
	at com.gentics.mesh.context.impl.InternalRoutingActionContextImpl.send(InternalRoutingActionContextImpl.java:80)
	at com.gentics.mesh.handler.ActionContext.send(ActionContext.java:78)
	at com.gentics.mesh.search.index.AbstractSearchHandler.lambda$query$14(AbstractSearchHandler.java:274)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:61)
	at io.reactivex.internal.operators.observable.ObservableCollectSingle$CollectObserver.onComplete(ObservableCollectSingle.java:121)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.drainLoop(ObservableFlatMapSingle.java:254)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.drain(ObservableFlatMapSingle.java:210)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.onComplete(ObservableFlatMapSingle.java:133)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onComplete(ObservableOnErrorNext.java:115)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:60)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient$1.onResponse(ElasticsearchOkClient.java:150)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "OkHttp http://localhost:9200/..." java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:547)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:188)
	at com.gentics.mesh.context.impl.InternalRoutingActionContextImpl.send(InternalRoutingActionContextImpl.java:80)
	at com.gentics.mesh.handler.ActionContext.send(ActionContext.java:78)
	at com.gentics.mesh.search.index.AbstractSearchHandler.lambda$query$14(AbstractSearchHandler.java:274)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:61)
	at io.reactivex.internal.operators.observable.ObservableCollectSingle$CollectObserver.onComplete(ObservableCollectSingle.java:121)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.drainLoop(ObservableFlatMapSingle.java:254)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.drain(ObservableFlatMapSingle.java:210)
	at io.reactivex.internal.operators.observable.ObservableFlatMapSingle$FlatMapSingleObserver.onComplete(ObservableFlatMapSingle.java:133)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onComplete(ObservableOnErrorNext.java:115)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:60)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
	at com.gentics.elasticsearch.client.okhttp.ElasticsearchOkClient$1.onResponse(ElasticsearchOkClient.java:150)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
08:57:10.564 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-4] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:57:10 GMT] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"




08:59:31.453 [Joyful Sneasel] INFO  [vert.x-eventloop-thread-6] - 172.17.0.1 - - [Wed, 21 Nov 2018 08:59:31 GMT] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"
^CNov 21, 2018 9:04:47 AM com.orientechnologies.common.log.OLogManager log
WARNING: Received signal: SIGINT
Nov 21, 2018 9:04:47 AM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
Nov 21, 2018 9:04:47 AM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: storage...
Nov 21, 2018 9:04:48 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete
09:04:48.959 [Joyful Sneasel] INFO  [Thread-0] - Mesh shutting down...
09:04:49.959 [Joyful Sneasel] INFO  [Thread-3] - Terminating Elasticsearch process..
^C^C^C^C^C

```

**Comment by cschockaert** [comment] 2018-11-21 09:37
Perhaps its because binaryUuid is the same for every nodes and saving this binary to filesystem is a blocking action server side?

**Comment by Jotschi** [comment] 2018-11-21 09:41
@cschockaert I have the impression it has something to do with the Elasticsearch sync process. You could try to disable ES integration by setting `MESH_ELASTICSEARCH_START_EMBEDDED` to false and `MESH_ELASTICSEARCH_URL` to null. 

If it works in that case it means that the ES sync is blocking the process.

**Comment by cschockaert** [comment] 2018-11-21 09:49
i dont think i can test easyly with this setting coz my batch is relying on elasticsearch result to start.

i made another test, client side i used only 1 eventloop thread:
```
Vertx.vertx(new VertxOptions().setEventLoopPoolSize(1))
```

and now it's working fine ! 

so it's definitively something about a race condition and same binary uuid

**Comment by cschockaert** [comment] 2018-11-21 09:50
this code seems weird : a blocking get inside a onNext() ? 

![image](https://user-images.githubusercontent.com/8597973/48833233-358d1980-ed7b-11e8-866c-44d4d8b993f2.png)

**Comment by Jotschi** [comment] 2018-11-21 10:13
@cschockaert I'm going to write a testcase to try to reproduce the issue.

**Comment by cschockaert** [comment] 2018-11-21 10:15
@Jotschi thanks, i'm updating my batch to upload != binary in parallel and see if the problem is no here.
this would indicate if its linked to the fact that we want to store the same file in // in the filesystem

**Comment by Jotschi** [comment] 2018-11-21 20:21
@cschockaert I added a test which can reproduce the issue. You are absolutely right. A `blockingGet()` within the loop will cause the lockup.

**Comment by cschockaert** [comment] 2018-11-22 06:45
Thanks for your responsiveness!
Apart that i Saw a S3 impl of storage. How can we activate it?

**Comment by Jotschi** [comment] 2018-11-22 10:35
@cschockaert Thats not yet finished since I wanted to wait until the AWS S3 reactive connector is ready.

**Comment by Jotschi** [comment] 2019-02-22 14:26
Issue will be fixed with one of the next releases. I reworked the upload code - We hope to ship this with 0.31.0

**Comment by cschockaert** [comment] 2019-03-05 20:17
ok @Jotschi another reason for us to upgrade to the latest release

**Comment by Jotschi** [comment] 2019-05-15 18:48
Change has been added to 0.32.0 - I'm going to close this issue. If you notice any other issue regarding dead locks feel free to open an issue.

**Closed by Jotschi** 2019-05-15 18:48 UTC
Labels: bug, f/rest
